services:
    lavalink:
        image: ghcr.io/lavalink-devs/lavalink:4.0.8

        cpu_period: 50000
        cpu_quota: 25000
        mem_limit: 512m

        ports:
            - '2333:2333'
        environment:
            - LAVALINK_PASSWORD="password"
        volumes:
            - ./application.yml:/opt/Lavalink/application.yml:ro
            - ./plugins:/opt/Lavalink/plugins:ro

    discord-bot:
        cpu_period: 50000
        cpu_quota: 25000
        mem_limit: 512m

        build:
            context: .
            dockerfile: Dockerfile

        ports:
            - '3000:3000'

        volumes:
            - .:/usr/src/app:delegated
