name: CI

on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    environment: SpiderBot
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USUARIO }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          command: cd ./SpiderBot && git pull