name: CI

on: [push]

jobs:
  deploy:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@v1.0.2
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USUARIO }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: cd ./SpiderBot && git pull